#    Basic

1. Write a Python program to check if a given number is positive or negative.

In [3]:
a=int(input("enter a number:"))
if a>0:
    print("positive")
else:
        print("negative")

enter a number:-2
negative


2. Create a program that determines if a person is eligible to vote based on their age.


In [5]:
age=int(input("enter a number:"))
if age>=18:
    print("eligible to vote")
else:
    print("age is below 18")

enter a number:12
age is below 18


3. Develop a program to find the maximum of two numbers using if-else statements.


In [7]:
a1=100
a2=200
if a1>a2:
    print("a1 is greater")
else:
    print("a2 is greater")

a2 is greater


4. Write a Python script to classify a given year as a leap year or not.


In [39]:
a=int(input ('enter the year:'))
if (a%4==0 and a%100!=0 or a%400==0):
    print(a,'is a leap year')
else:
        print(a,'is not a leap year')

enter the year:2016
2016 is a leap year


5. Create a program that checks whether a character is a vowel or a consonant.


In [9]:
a1=input("enter a character: ")
a1.lower()
if a1=="a" or a1=="e" or a1=="i" or a1=="o" or a1=="u":
    print("character is a vowel")
else:
    print("character is not a vowel")

enter a character: b
character is not a vowel


6. Implement a program to determine whether a given number is even or odd.


In [12]:
num=int(input("enter a number:"))
if num%2==0:
    print("even number")
else:
    print("odd number")

enter a number:5
odd number


7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.


In [24]:
def my_abs(value):
    if value>=0:
        return(value)
    else:
        return(value*-1)
        
print(my_abs(10))
print(my_abs(-20))

10
20


8. Develop a program that determines the largest of three given numbers using if-else statements.


In [33]:
n1=int(input("enter a number:"))
n2=int(input("enter a number:"))
n3=int(input("enter a number:"))

if n1>n2 and n1>n3:
    print("largest is n1")
if n2>n1 and n2>n3:
    print("largest is n2")
if n3>n1 and n3>n2:
    print("largest is n3")

enter a number:10
enter a number:20
enter a number:5
largest is n2


9. Create a program that checks if a given string is a palindrome.


In [13]:
string=input("enter a string: ")
if (string==string[::-1]):
    print(string,"is a palindrome")
else:
    print(string,"is not a palindrome")
    

enter a string: malayalam
malayalam is a palindrome


10. Write a Python program to calculate the grade based on a student's score.

In [7]:
score=int(input("enter a score value:"))
if score>=90:
    print("Grade O+")
elif score>=70 and score<90:
    print("Grade A")
elif score>=50 and score<70:
    print("Grade B")
else:
    print("Grade C")
    

enter a score value:34
Grade C


# Nested if else statement

11. Write a program to find the largest among three numbers using nested if-else statements.

In [32]:
n1=int(input("enter a number:"))
n2=int(input("enter a number:"))
n3=int(input("enter a number:"))

if n1>n2:
    print("largest is n1")
elif n2>n3:
    print("largest is n2")
else:
    print("largest is n3")

enter a number:45
enter a number:55
enter a number:200
largest is n3


12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.


In [46]:
def checkTriangle(x,y,z):
    if x==y==z:
        print("equilateral triangle")
    elif x==y or y==z or z==x:
        print("Isosceles triangle")
    else:
        print("scalene triangle")
        
checkTriangle(8,7,9)

scalene triangle


13. Develop a program that checks if a year is a leap year and also if it is a century year.


In [44]:
i=int(input("enter a year:"))

if (i%4==0 and i%100!=0 or i%400==0):
    print("it is a leap year and a century year")
else:
    print("not a century year")
    
#if (i%4==0 and i%100==0 or i%400!=0):
 #   print("century year")

    

enter a year:2016
it is a leap year and a century year


14. Write a Python script to determine if a number is positive, negative, or zero.


In [49]:
num=int(input("enter a number: "))
if num>0:
    print("positive")
elif num==0:
    print("zero")
else:
    print("negative")

enter a number: -9
negative


15. Create a program to check if a person is a teenager (between 13 and 19 years old).


In [56]:
age=int(input("enter a number:"))
if age>=13 and age<=19:
    print("person is a teenager")
else:
     print("person is not a teenager")          

enter a number:15
person is a teenager


16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).


In [17]:
def angle_type(a,b,c):
    a_sq=pow(a,2) # a**2
    b_sq=pow(b,2)
    c_sq=pow(c,2)
    if (c_sq==a_sq+b_sq or b_sq==c_sq+b_sq or a_sq==c_sq+b_sq ): # c**2=a**2+b**2
        print("right angle ")
    elif (c_sq>a_sq+b_sq or b_sq>c_sq+b_sq or a_sq>c_sq+b_sq ): # c**2>a**2+b**2
        print("Obtuse angle ")
    else:
        print("Acute angle ") ## c**2<a**2+b**2

In [18]:
angle_type(10,6,8)

right angle 


In [19]:
angle_type(5,7,8)

Acute angle 


In [20]:
angle_type(12,7,3)

Obtuse angle 


17. Write a Python program to calculate the roots of a quadratic equation.


In [8]:
import math

In [9]:
def findroot(a,b,c):
    if a==0:
        print("invalid")
        return -1
    d=b*b-4*a*c
    sqrt_val=math.sqrt(abs(d))
    
    if d>0:
        print("roots are real and different")
        print((-b+sqrt_val)/(2*a))
        print((-b+sqrt_val)/(2*a))
    elif d==0:
        print("roots are real and same")
        print(-b/(2*a))
    else:
        print("roots are complex")
        print(-b/(2*a),"+i",sqrt_val)
        print(-b/(2*a),"-i",sqrt_val)
findroot(1,4,4)

roots are real and same
-2.0


18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2
for Tuesday, etc.).

In [7]:
day=int(input("enter a number :"))

if day==1:
        print("monday")
elif day==2:
        print("Tuesday")
elif day==3:
        print("Wednesday")
elif day==4:
        print("Thursday")
elif day==5:
        print("Friday")
elif day==6:
        print("Saturday")
else:
        print("sunday")
       

enter a number :3
Wednesday


19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.


In [1]:
i=int(input("enter a year:"))

if (i%4==0 or i%400==0):
    print("it is a leap year ")
else:
    print("not a leap year")

enter a year:2016
it is a leap year 


20. Develop a program that checks if a given number is prime or not using nested if-else statements.

In [12]:
n=int(input("enter a number:"))

if n>1:
    for i in range(2,int(n/2)+1): 
        if n%i==0:
            print(n,"is not a prime number")
            break
    else:
            print(n,"is a prime number")
            
else:
        print(n,"is not a prime number")

enter a number:2
2 is a prime number


# Elif statement

21. Write a Python program to assign grades based on different ranges of scores using elif statements.

In [14]:
score=int(input("enter a score value:"))
if score>=90:
    print("Grade O+")
elif score>=70 and score<90:
    print("Grade A")
elif score>=50 and score<70:
    print("Grade B")
else:
    print("Grade C")

enter a score value:54
Grade B


22. Implement a program to determine the type of a triangle based on its angles.


In [31]:
# import math
x=int(input('enter the first angle: '))
# print("degrees(x):",math.degrees(x))
y=int(input('enter the second angle: '))
# print("degrees(y):",math.degrees(y))
z=int(input('enter the third angle: '))
# print("degrees(z):",math.degrees(z))


if x==y==z:
    print("equilateral triangle")
elif x==y or y==z or x==z:
    print("Isosceles triangle")
else:
    print("scalene triangle")


enter the first angle: 45
enter the second angle: 45
enter the third angle: 45
equilateral triangle


23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
elif statements.

In [39]:
BMI=float(input("BMI of a person:"))

if BMI<18.5:
    print("Under weight ")
elif (BMI>=18.5 and BMI<24.9):
    print("Normal")
elif (BMI>=20.0 and BMI<29.9):
    print("overweight")
else:
    print("obese")
    

BMI of a person:30
obese


24. Create a program that determines whether a given number is positive, negative, or zero using elif
statements.

In [15]:
num=int(input("enter a number: "))
if num>0:
    print("positive")
elif num==0:
    print("zero")
else:
    print("negative")

enter a number: 5
positive


25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif
statements.

In [23]:
characters= input("enter a character: ")
import re
if re.match(r'[a-z]+',characters):
    print("lower")
elif re.match(r'[A-Z]+',characters):
    print("upper")
elif re.match(r'[0-9]+',characters):
    print("digit")
else:
    print(characters,"is non alphanumeric")

enter a character: hello
lower


26. Implement a program to calculate the discounted price based on different purchase amounts using elif
statements.

In [26]:
product_price=int(input("enter the amount:"))

if product_price>3000:
    print("the price of product is {}".format(product_price*0.8)) # 20% discount
elif product_price>=2000 and product_price<=3000:
    print("the price of product is {}".format(product_price*0.7)) # 30% discount
elif product_price>=1000 and product_price<2000:
    print("the price of product is {}".format(product_price*0.6)) # 40% discount
else:
    print("lets drink tea")
    

enter the amount:2000
the price of product is 1400.0


27. Develop a program to calculate the electricity bill based on different consumption slabs using elif
statements.

In [1]:
# 1 to 100 units- Rs: 10/unit
# 100 to 200 units- Rs: 15/unit
# 200 to 300 units- Rs: 20/unit
# above 300 units- Rs: 25/unit
unit=int(input("Enter your unit: "))
if unit<100:
    bill=unit*10
elif unit>=100 and unit<200:
    bill=(100*10)+(unit-100)*15
elif unit>=200 and unit<300:
    bill=(100*10)+(100*15)+(unit-200)*20
else:
    bill=(100*10)+(100*15)+(100*20)+((unit-300)*25)
    
print("Rs:",bill,"to be paid for",unit,"units")

Enter your unit: 250
Rs: 3500 to be paid for 250 units


28. Create a program to determine the type of quadrilateral based on its angles and sides using elif
statements.

In [4]:
# ===== enter the sides=====
side_1=input("enter side 1: )
side_2=input("enter side 2: )
side_3=input("enter side 3: )
side_4=input("enter side 4: )
             
angle_1=input("enter angle 1: ")
angle_2=input("enter angle 2: ")
angle_3=input("enter angle 3: ")
angle_4=input("enter angle 4: ")


             
 
    
    


SyntaxError: invalid syntax (<ipython-input-4-6750e6fbd29c>, line 1)

29. Write a Python script to determine the season based on a user-provided month using elif statements.


In [4]:
month=input("enter a month: ")

if month in ("februrary","march"):
    print("spring season")
elif month in ("april","may","june"):
    print("summer season")
elif month in ("july","augusut","september"):
    print("monsoon season")
elif month in ("october","november"):
    print("autumn season")
else:
    print("winter season")

enter a month: january
winter season


30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
elif statements.

In [3]:
year=int(input("enter a year "))
month=int(input("enter a month: "))
if ((year%4==0 and year%100!=0) or (year%400==0)) and (month==2): # IF leap year then 29 days
    print("leap year and number of days is 29")
elif month==2: # not a leap year
    print("number of days is 28")
elif (month==1)or (month==3)or (month==5)or (month==7)or (month==8)or(month==10)or(month==12):
    print("number of days is 31")
else:

    print("number of days 30")

enter a year 2023
enter a month: 2
number of days is 28


# Basic level

1. Write a Python program that checks if a given number is positive, negative, or zero.

In [5]:
a=int(input("enter a number:"))
if a>0:
    print("positive")
elif a==0:
    print("zero")
else:
    print("negative")

enter a number:3
positive


2. Create a program to determine if a person is eligible to vote based on their age.


In [6]:
age=int(input("enter a number:"))
if age>=18:
    print("eligible to vote")
else:
    print("age is below 18")

enter a number:19
eligible to vote


3. Write a program to find the maximum of two given numbers using conditional statements.


In [7]:
a1=100
a2=200
if a1>a2:
    print("a1 is greater")
else:
    print("a2 is greater")

a2 is greater


4. Develop a program that calculates the grade of a student based on their exam score.


In [8]:
score=int(input("enter a score value:"))
if score>=90:
    print("Grade O+")
elif score>=70 and score<90:
    print("Grade A")
elif score>=50 and score<70:
    print("Grade B")
else:
    print("Grade C")
    

enter a score value:87
Grade A


5. Create a program that checks if a year is a leap year or not.


In [9]:
a=int(input ('enter the year:'))
if (a%4==0 and a%100!=0 or a%400==0):
    print(a,'is a leap year')
else:
        print(a,'is not a leap year')

enter the year:2016
2016 is a leap year


6. Write a program to classify a triangle based on its sides' lengths.


In [18]:
def checkTriangle(x,y,z):
    if x==y==z:
        print("equilateral triangle")
    elif x==y or y==z or z==x:
        print("Isosceles triangle")
    else:
        print("scalene triangle")
        
checkTriangle(8,7,9)

scalene triangle


7. Build a program that determines the largest of three given numbers.


In [10]:
n1=int(input("enter a number:"))
n2=int(input("enter a number:"))
n3=int(input("enter a number:"))

if n1>n2 and n1>n3:
    print("largest is n1")
if n2>n1 and n2>n3:
    print("largest is n2")
if n3>n1 and n3>n2:
    print("largest is n3")

enter a number:23
enter a number:35
enter a number:21
largest is n2


8. Develop a program that checks whether a character is a vowel or a consonant.


In [12]:
a1=input("enter a character: ")
a1.lower()
if a1=="a" or a1=="e" or a1=="i" or a1=="o" or a1=="u":
    print("character is a vowel")
else:
    print("character is not a vowel")

enter a character: e
character is a vowel


9. Create a program to calculate the total cost of a shopping cart based on discounts.


In [13]:
product_price=int(input("enter the amount:"))

if product_price>3000:
    print("the price of product is {}".format(product_price*0.8)) 
elif product_price>=2000 and product_price<=3000:
    print("the price of product is {}".format(product_price*0.7))
elif product_price>=1000 and product_price<2000:
    print("the price of product is {}".format(product_price*0.6))
else:
    print("lets drink tea")

enter the amount:2500
the price of product is 1750.0


10. Write a program that checks if a given number is even or odd.

In [15]:
a=int(input("enter a number: "))
if a%2==0:
    print("even number")
else:
    print("odd number")

enter a number: 3
odd number


# Intermediate level

11. Write a program that calculates the roots of a quadratic equation .

In [24]:
import math

def findroot(a,b,c):
    if a==0:
        print("invalid")
        return -1
    d=b*b-4*a*c
    sqrt_val=math.sqrt(abs(d))
    
    if d>0:
        print("roots are real and different")
        print((-b+sqrt_val)/(2*a))
        print((-b+sqrt_val)/(2*a))
    elif d==0:
        print("roots are real and same")
        print(-b/(2*a))
    else:
        print("roots are complex")
        print(-b/(2*a),"+i",sqrt_val)
        print(-b/(2*a),"-i",sqrt_val)
findroot(1,4,4)

roots are real and same
-2.0


12. Create a program that determines the day of the week based on the day number (1-7).


In [19]:
day=int(input("enter a number :"))

if day==1:
        print("monday")
elif day==2:
        print("Tuesday")
elif day==3:
        print("Wednesday")
elif day==4:
        print("Thursday")
elif day==5:
        print("Friday")
elif day==6:
        print("Saturday")
else:
        print("sunday")
       

enter a number :3
Wednesday


13. Develop a program that calculates the factorial of a given number using recursion.


In [22]:
def fact(n):
    if n==0:
        return 1
    else:
        return n*fact(n-1)

In [23]:
fact(5)

120

14. Write a program to find the largest among three numbers without using the `max()` function.


In [20]:
n1=int(input("enter a number:"))
n2=int(input("enter a number:"))
n3=int(input("enter a number:"))

if n1>n2 and n1>n3:
    print("largest is n1")
if n2>n1 and n2>n3:
    print("largest is n2")
if n3>n1 and n3>n2:
    print("largest is n3")

enter a number:10
enter a number:20
enter a number:12
largest is n2


15. Create a program that simulates a basic ATM transaction menu.


In [27]:
amount=int(input("enter the amount for transaction: "))

if amount!=0:
    print("take the cash")
else:
    print("ATM has no money, need to refill")

enter the amount for transaction: 100
take the cash


16. Build a program that checks if a given string is a palindrome or not.


In [25]:
a=input("enter a string: ")
if (a==a[::-1]):
    print(a,"is a  palindrome")
else:
    print(a,"is not a palindrome")

enter a string: radar
radar is a  palindrome


17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.


In [10]:
def centered_average(salary):
    salary.remove(min(salary))
    salary.remove(max(salary))
    return sum(salary)/len(salary)
salary=[8000,15000,25000,35000,250000]
print(centered_average(salary))

25000.0


18. Develop a program that converts a given temperature from Celsius to Fahrenheit.


In [5]:
c_temp=float(input("enter a temp:"))
fahrenheit=(c_temp*1.8)+32
print(fahrenheit,"in Fahrenheit")

enter a temp:20
68.0 in Fahrenheit


19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.


In [ ]:
a=int(input("enter a number,a: "))
b=int(input("enter a number,b: "))
operator=input("enter the operator: ")
if operator=="+":
    print(a+b)
elif operator=="-":
    print(a-b)
elif operator=="/":
    print(a/b)
elif operator=="*":
    print(a*b)
else:
    print("operator not defined")


20. Write a program that determines the roots of a cubic equation using the Cardano formula.

# Advance level

21. Create a program that calculates the income tax based on the user's income and tax brackets.

22. Write a program that simulates a rock-paper-scissors game against the computer.


In [4]:
import random
player_1=input("select Rock,Paper,or Scissors:").lower()
player_2=random.choice(["Rock","Paper","Scissors"]).lower()
print("Player 2 selected:",player_2)

if player_1=="rock" and player_2=="paper":
    print("Player_2 won")
elif player_1=="paper" and player_2=="scissors":
    print("Player_2 won")
elif player_1=="scissors" and player_2=="rock":
    print("Player_2 won")
elif player_1==player_2:
    print("Tie")
else:
    print("Player_1 won")

select Rock,Paper,or Scissors:rock
Player 2 selected: scissors
Player_1 won


23. Develop a program that generates a random password based on user preferences (length, complexity).


In [34]:
import string
import random

characters=list(string.ascii_letters+string.digits+"!@#$%&*?|:()")

def generate_random_password():
    length=int(input("enter the length of the password: "))
    random.shuffle(characters)
    password=[]
    for i in range(length):
        password.append(random.choice(characters))
    random.shuffle(password)
    print("".join(password))

In [35]:
generate_random_password()

enter the length of the password: 10
zjcnXU&2df


24. Create a program that implements a simple text-based adventure game with branching scenarios.


25. Build a program that solves a linear equation  for x, considering different cases.


26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.


27. Develop a program that determines whether a given year is a prime number or not.


In [44]:
a=int(input("enter a year: "))
if (a%4==0 or a%100!=0) and (a%400==0):
    print(a,"is a prime number")
else:
    print(a,"is not a prime number")
    

enter a year: 2000
2000 is a prime number


28. Create a program that sorts three numbers in ascending order using conditional statements.


In [8]:
a=float(input("enter a:"))
b=float(input("enter b:"))
c=float(input("enter c:"))
if a>b:
    a,b=b,a
if a>c:
    a,c=c,a
if b>c:
    b,c=c,b
print(a,"<",b,"<",c)

enter a:23
enter b:33
enter c:11
11.0 < 23.0 < 33.0


29. Build a program that determines the roots of a quartic equation using numerical methods.


30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based 

In [5]:
BMI=float(input("BMI of a person:"))

if BMI<18.5:
    print("Under weight ")
elif (BMI>=18.5 and BMI<24.9):
    print("Normal")
elif (BMI>=20.0 and BMI<29.9):
    print("overweight")
else:
    print("obese")
    

BMI of a person:19
Normal


# challenge level


31. Create a program that validates a password based on complexity rules (length, characters, etc.).

In [10]:
import string
import random

characters=list(string.ascii_letters+string.digits+"!@#$%&*?|:()")

def generate_random_password():
    length=int(input("enter the length of the password: "))
    random.shuffle(characters)
    password=[]
    for i in range(length):
        password.append(random.choice(characters))
    random.shuffle(password)
    print("".join(password))

In [11]:
generate_random_password()

enter the length of the password: 12
4v&Z8ZjLmEm$


32. Develop a program that performs matrix addition and subtraction based on user input.


In [20]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print("element of first matrix")
print(a)
print("element of second matrix")
print(b)
print("addition of two matrix")
print(np.add(a,b))


element of first matrix
[[1 2]
 [3 4]]
element of second matrix
[[4 5]
 [6 7]]
addition of two matrix
[[ 5  7]
 [ 9 11]]


In [21]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print("element of first matrix")
print(a)
print("element of second matrix")
print(b)
print("substraction of two matrix")
print(np.subtract(a,b))

element of first matrix
[[1 2]
 [3 4]]
element of second matrix
[[4 5]
 [6 7]]
substraction of two matrix
[[-3 -3]
 [-3 -3]]


33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
algorithm.


In [32]:
def gcd(a,b):
    if(a==0):
        return b
    if(b==0):
        return a
    if (a==b):
        return a
    if (a>b):
        return gcd(a-b,b)
    return gcd(a,b-a)
a=98
b=56
if(gcd(a,b)):
    print("GCD of",a,'and',b,'is',gcd(a,b))
else:
    print("not found")


GCD of 98 and 56 is 14


34. Build a program that performs matrix multiplication using nested loops and conditional statements.


In [38]:
x=[[12,7,3],
  [4,5,6],
  [7,8,9]]
y=[[5,8,1,2],
  [6,7,3,0],
  [4,5,9,1]]

result=[[0,0,0,0],
       [0,0,0,0],
       [0,0,0,0]]

for i in range(len(x)):
     for j in range(len(y[0])):
        for k in range(len(y)):
            result[i][j]+=x[i][k]*y[k][j]
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]
